# Numpy

In [1]:
import numpy as np

In [5]:
M = [[1,2,5],[3,4,6]]

In [7]:
M = np.array(M)

In [9]:
M.shape

(2, 3)

In [11]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
def matrix_multiplication(M,N): 
    # List to store matrix multiplication result 
    R = [[0, 0, 0, 0],  
        [0, 0, 0, 0],  
        [0, 0, 0, 0], 
        [0, 0, 0, 0]]  
  
    for i in range(0, 4):  
        for j in range(0, 4): 
            for k in range(0, 4):  
                R[i][j] += M[i][k] * N[k][j]  
  
    return R
  
# First matrix. M is a list 
M = [[1, 1, 1, 1],  
    [2, 2, 2, 2],  
    [3, 3, 3, 3], 
    [4, 4, 4, 4]] 
  
# Second matrix. N is a list 
N = [[1, 1, 1, 1],  
    [2, 2, 2, 2],  
    [3, 3, 3, 3], 
    [4, 4, 4, 4]]  
      
# Call matrix_multiplication function 


In [25]:
import time
start = time.time()
for i in range(50000):
    M = matrix_multiplication(M,N)
time.time()-start

KeyboardInterrupt: 

In [26]:
M = [[1, 1, 1, 1],  
    [2, 2, 2, 2],  
    [3, 3, 3, 3], 
    [4, 4, 4, 4]] 
  
# Second matrix. N is a list 
N = [[1, 1, 1, 1],  
    [2, 2, 2, 2],  
    [3, 3, 3, 3], 
    [4, 4, 4, 4]] 

In [27]:
M = np.array(M)
N = np.array(N)
start = time.time()
for i in range(50000):
    M = M.dot(N)
time.time()-start

0.1272721290588379

In [38]:
#Broadcasting

M = [[1, 1, 1, 1],  
    [2, 2, 2, 2],  
    [3, 3, 3, 3], 
    [4, 4, 4, 4]] 

M = np.array(M)

In [39]:
M

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [40]:
N = np.array([[2]])

In [42]:
Z = M*N

In [44]:
Z

array([[2, 2, 2, 2],
       [4, 4, 4, 4],
       [6, 6, 6, 6],
       [8, 8, 8, 8]])

In [45]:
Z.T

array([[2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8],
       [2, 4, 6, 8]])

In [50]:
Z.reshape(1,16)

array([[2, 2, 2, 2, 4, 4, 4, 4, 6, 6, 6, 6, 8, 8, 8, 8]])

In [52]:
# 16 = 4x4 = 2x8 = 8x2 = 16x1.....
Z.reshape(2,8)

array([[2, 2, 2, 2, 4, 4, 4, 4],
       [6, 6, 6, 6, 8, 8, 8, 8]])