In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Numpy

In [3]:
def matrix_multiplication(M,N): 
    # List to store matrix multiplication result 
    R = [[0, 0, 0, 0],  
        [0, 0, 0, 0],  
        [0, 0, 0, 0], 
        [0, 0, 0, 0]]  
  
    for i in range(0, 4):  
        for j in range(0, 4): 
            for k in range(0, 4):  
                R[i][j] += M[i][k] * N[k][j]  
  
    return R
  

In [25]:
# First matrix. M is a list 
M = [[1, 1, 1, 1],  
    [2, 2, 2, 2],  
    [3, 3, 3, 3], 
    [4, 4, 4, 4]] 
  
# Second matrix. N is a list 
N = [[1, 1, 1, 1],  
    [2, 2, 2, 2],  
    [3, 3, 3, 3], 
    [4, 4, 4, 4]]  

In [23]:
import time

In [24]:
start = time.time()
for i in range(5000):
    M = matrix_multiplication(M,N)
print(time.time()-start)

0.670015811920166


In [26]:
M = np.array(M)
N = np.array(N)

In [27]:
start = time.time()
for i in range(5000):
    M = np.dot(M,N)
print(time.time()-start)

0.014531850814819336


In [30]:
A = np.array([[[1],[2],[3]],[[4],[5],[6]]])

In [31]:
A.shape

(2, 3, 1)

In [37]:
C = np.zeros((4,5))

In [33]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
B = np.eye(5)

In [40]:
X = np.dot(C,B)

In [42]:
Y = np.empty((4,5))

In [44]:
X * Y

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
X = np.ones((4,4))
Y = np.zeros((1,1))

In [62]:
print(X)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [63]:
print(Y)

[[0.]]


In [64]:
X*Y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [66]:
N = [[1, 1, 1, 1],  
    [2, 2, 2, 2],  
    [3, 3, 3, 3], 
    [4, 4, 4, 4]]  
N = np.array(N)

In [68]:
N.reshape()

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [72]:
N.reshape(2,8)

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [3, 3, 3, 3, 4, 4, 4, 4]])

In [73]:
N.reshape(1,16)

array([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]])

In [75]:
N.T

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])